models/policy_action.py
from models.mongua import Mongua
from flask import session


class Policy_action(Mongua):
    __fields__ = Mongua.__fields__ + [
        ('section', str, ''),
        ('weight_name', str, ''),
        ('hot_name', str, ''),
        ('position', str, ''),
        ('time', str, ''),
        ('policy', str, ''),
    ]

    def __init__(self):
        pass

    @classmethod
    # 存入指数
    def index_register(cls, form):
        u = Policy_action.new(form)
        u.id = session.get('user_id', -1)
        return u

models/weight_action.py
from models.mongua import Mongua
from flask import session


class Weight_action(Mongua):
    __fields__ = Mongua.__fields__ + [
        ('section', str, ''),
        ('quantity', str, ''),
        ('central', str, ''),
        ('position', str, ''),
        ('line', str, ''),
        ('name', str, ''),
    ]

    def __init__(self):
        pass

    @classmethod
    # 存入指数
    def index_register(cls, form):
        u = Weight_action.new(form)
        u.id = session.get('user_id', -1)
        return u

routes/topic.py
from flask import (
    render_template,
    request,
    session,
    redirect,
    url_for,
    Blueprint,
)

from models.market_index import Market_index
from models.weight_action import Weight_action
from models.policy_action import Policy_action
from routes.index import login_client

main = Blueprint('topic', __name__)


# 获取最新指数价量异动
@main.route('/')
def index():
    # 获得最大id
    # query = {}
    # df = mongua.xx['Market_index'].find(query, {'id': 1, '_id': 0}).sort('id', -1).limit(1)
    # max_id = [x['id'] for x in df][0]
    if login_client():
        return redirect(url_for('index.index'))
    uid = session.get('user_id', -1)
    uu = Market_index.find_all(user_id=uid)
    ss = Weight_action.find_all(user_id=uid)
    pp = Policy_action.find_all(user_id=uid)
    return render_template('topic/index.html', u=uu, s=ss, p=pp)


@main.route('/instruction1')
def instruction1():
    if login_client():
        return redirect(url_for('index.index'))
    return render_template('topic/instruction1.html')


@main.route('/instruction2')
def instruction2():
    if login_client():
        return redirect(url_for('index.index'))
    return render_template('topic/instruction2.html')


@main.route('/instruction3')
def instruction3():
    if login_client():
        return redirect(url_for('index.index'))
    return render_template('topic/instruction3.html')


@main.route('/instruction4')
def instruction4():
    if login_client():
        return redirect(url_for('index.index'))
    return render_template('topic/instruction4.html')

#指数价量异动页面显示
@main.route('/admin')
def admin():
    if login_client():
        return redirect(url_for('index.index'))
    uid = session.get('user_id', -1)
    uu = Market_index.find_all(user_id=uid)
    return render_template('topic/admin.html', u=uu)


@main.route('/weight')
def weight():
    if login_client():
        return redirect(url_for('index.index'))
    uid = session.get('user_id', -1)
    uu = Weight_action.find_all(user_id=uid)
    return render_template('topic/weight.html', u=uu)


@main.route('/policy')
def policy():
    if login_client():
        return redirect(url_for('index.index'))
    uid = session.get('user_id', -1)
    uu = Policy_action.find_all(user_id=uid)
    return render_template('topic/policy.html', u=uu)

#指数价量异动保存
@main.route('/market_index', methods=['POST'])
def market_index():
    if login_client():
        return redirect(url_for('index.index'))
    form = request.form
    uu = Market_index.index_register(form)
    return redirect(url_for('.admin'))


@main.route('/weight_index', methods=['POST'])
def weight_index():
    if login_client():
        return redirect(url_for('index.index'))
    form = request.form
    Weight_action.index_register(form)
    return redirect(url_for('.weight'))


@main.route('/policy_index', methods=['POST'])
def policy_index():
    if login_client():
        return redirect(url_for('index.index'))
    form = request.form
    Policy_action.index_register(form)
    return redirect(url_for('.policy'))


@main.route("/delete")
def delete():
    if login_client():
        return redirect(url_for('index.index'))
    id = int(request.args.get('id'))
    uid = session.get('user_id', -1)
    w = Weight_action.find_one(id=id, user_id=uid)
    Weight_action.delete(w)
    return redirect(url_for('.weight'))



@main.route("/delete1")
def delete1():
    if login_client():
        return redirect(url_for('index.index'))
    id = int(request.args.get('id'))
    uid = session.get('user_id', -1)
    w = Policy_action.find_one(id=id, user_id=uid)
    Policy_action.delete(w)
    return redirect(url_for('.policy'))



@main.route("/delete3")
def delete3():
    if login_client():
        return redirect(url_for('index.index'))
    id = int(request.args.get('id'))
    uid = session.get('user_id', -1)
    w = Market_index.find_one(id=id, user_id=uid)
    Market_index.delete(w)
    return redirect(url_for('.admin'))

templates/topic/admin.html
<!DOCTYPE html>

<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0"><link rel="shortcut icon" href="../../static/topic/index/static/images/notebook_ico.ico" type="image/x-icon" />
    <title>复盘笔记本 - 每日数据</title>
    <meta name="keywords" content="复盘笔记本,数据可视化，股市量化分析">
    <meta name="description" content="复盘笔记本产品slogan">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/font-awesome.min.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/base.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/page.css">
       <link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
</head>
<body class="oneday">
<div class="placeHeader"></div>
<header>
    <div class="logo"><img src="../../static/topic/index/static/images/notebook.png"><p>复盘笔记本</p><div class="clear"></div></div>
<ul class="menu">
    <li class="curMenu"><a href="/topic">建仓or清仓?(大盘异动)</a></li>
    <li ><a href="/topic1">换仓?(短期情绪)</a></li>
    <li><a href="/topic2">辅助工具</a></li>
  <li><a href="/topic/instruction1">使用说明</a></li>
    </ul>
<ul class="account">
    <li><a href="/topic2/user">我的账户</a></li>
 <li><a href="/">退出</a></li>
</ul>
<style>
    .mb2{
	text-align:center;
}
    .submit {
	padding: 6px;
	width:100px;
}
    .time{
    float:right;
    padding-right:20px;
    }
    .text1 {
    padding: 3px;
    border: 1px solid #cdcdcd;
    width: 700px;
}

</style></header>
<section class="contain">
    <aside>
        <ul>
            <li class="menu1"><a href="/topic">总结</a></li>
            <li class="menu2 curMenu"><a href="/topic/admin">指数价量异动</a></li>
            <li class="menu3"><a href="/topic/weight">权重异动</a></li>
            <li class="menu4 "><a href="/topic/policy">政策及权重调控</a></li>
        </ul>
    </aside>
    <section class="main" id="main">
        <div class="dateSelect">
            <span>长短期指数异动</span>
        </div>
        <section class="content tab">
            <div class="listThCover"><span></span></div>
            <ul class="list">
                <li class="th">
                     <ul>
                        <li class="td1"><span>指数名称</span></li>
                        <li class="td2">&nbsp</li>
                        <li class="td3"><a  class="sort" stype="sz">量能异动</a></li>
                        <li class="td4"><a  class="sort down" stype="time">结构位置</a></li>
                        <li class="td4"><a  class="sort down" stype="time">中枢</a></li>
                        <li class="td4"><a  class="sort down" stype="time">时间</a></li>
                        <li class="td7">其他</li>
                    </ul>
                </li>
            </ul>
                <ul class="list" id="gpList">
                {% for x in u %}
                <li class="tr ops" aid="undefined">
                    <ul><li class="td1">
                            {{x.index}}
                    </li>
                        <li class="td2" style="color: #61a0ff;">
                            <a  href="{{ url_for('topic.delete3', id=x.id, token=token) }}">
                                删除
                            </a>
                        </li>
                        <li class="td3">
                            {{x.quantity}}
                        </li>
                        <li class="td4">
                            {{x.position}}
                        </li>
                         <li class="td4">
                            {{x.central}}
                        </li>
                         <li class="td4">
                            {{x.time}}
                        </li>
                        <li class="td7">
                            {{x.tips}}
                        </li>
                    </ul>
                </li>
                {% endfor %}
                </ul>

        </section>
        <section class="content tab">
            <div class="listThCover"><span></span></div>
            <ul class="list">
                <li class="th">
                    <ul>
                <li class="td1"><span>指数名称</span></li>
                        <li class="td2">&nbsp</li>
                        <li class="td3"><a  class="sort" stype="sz">量能异动</a></li>
                        <li class="td4"><a  class="sort down" stype="time">结构位置</a></li>
                        <li class="td4"><a  class="sort down" stype="time">中枢</a></li>
                        <li class="td4"><a  class="sort down" stype="time">时间</a></li>
                        <li class="td7">其他</li>
                    </ul>
                </li>
            </ul>
            <form class="form-horizontal" method="post" action="{{ url_for('.market_index') }}">
                <ul class="list" id="gpList">
                <li class="tr ops" aid="undefined">
                    <ul>
                        <li class="td1">
                        <input name="index" class="text" type="text" value="指数名称">
                        </li>
                        <li class="td2" style="color: #61a0ff;">
                         <input name="delect" class="text" type="text" value="" disabled>
                        </li>
                        <li class="td3">
                            <input name="quantity" class="text" type="text" value="量能异动">
                        </li>
                        <li class="td4">
                            <input name="position" class="text" type="text" value="结构位置">
                        </li>
                         <li class="td4">
                            <input name="central" class="text" type="text" value="中枢">
                        </li>
                         <li class="td4">
                            <input name="time" class="text" type="text" value="时间">
                        </li>
                        <li class="td7">
                            <input name="tips" class="text1" type="text" value="其他">
                        </li>
                    </ul>
                </li>
                </ul>
                <div class="mb2">
                    <input type="submit" class="act-but submit" value="提交" id="btn_register">
                </div>
            </form>
        </section>
    </section>
</section>

<footer>    <div class="contain">        <p class="title">            <span class="item">关于我们</span>            <a href="/topic/instruction1">使用教程</a>            <span class="item">联系我们</span>            <a href="">联系方式</a>            <a href="">意见反馈</a>        </p>        <p class="copyright">Copyright ©2018  All Rights Reserved. 浙ICP备16009637号-3.</p>    </div></footer>
<script type="text/javascript">

templates/topic/instruction1.html
<!DOCTYPE html>

<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0"><link rel="shortcut icon" href="../../static/topic/index/static/images/notebook_ico.ico" type="image/x-icon" />
    <title>复盘笔记本 - 使用说明</title>
    <meta name="keywords" content="复盘笔记本,行情平台,股市行情,今日股市行情">
    <meta name="description" content="复盘笔记本产品slogan">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <link rel="stylesheet" href="../../static/topic/instruction/css/base.css">
    <link rel="stylesheet" href="../../static/topic/instruction/css/pagination.css">
    <link rel="stylesheet" href="../../static/topic/instruction/css/page.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/font-awesome.min.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/base.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/page.css">
    <link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
</head>
<body class="course article">
<div class="placeHeader"></div>
<header>
    <div class="logo"><img src="../../static/topic/index/static/images/notebook.png"><p>复盘笔记本</p><div class="clear"></div></div>
<ul class="menu">
    <li ><a href="/topic">建仓or清仓?(大盘异动)</a></li>
    <li ><a href="/topic1">换仓?(短期情绪)</a></li>
    <li><a href="/topic2">辅助工具</a></li>
    <li class="curMenu"><a href="/topic/instruction1">使用说明</a></li>
    </ul>
<ul class="account">
    <li><a href="/topic2/user">我的账户</a></li>
 <li><a href="/">退出</a></li>
</ul></header>
<section class="contain" id="main">
    <aside>
        <ul>
            <li class="menu1 curMenu"><a href="/topic/instruction1">大纲流程图</a></li>
            <li class="menu2"><a href="/topic/instruction2">是否建仓?</a></li>
            <li class="menu3"><a href="/topic/instruction3">建仓时间</a></li>
            <li class="menu4"><a href="/topic/instruction4">建仓标的</a></li>

        </ul>
    </aside>
    <section class="main" id="main">
        <div class="dateSelect">
            <span>使用说明</span>
        </div>
        <section class="content">
            <div style="text-align: center">
                <img src="../../static/topic/instruction/tool_images/交易体系.png">
                <p>
                    解决问题:
                        1.复盘反复浏览信息,求全,浪费时间
                        2.形成模型,优化模型
                </p>
            </div>
        </section>
    </section>
</section>

<footer>    <div class="contain">        <p class="title">            <span class="item">关于我们</span>            <a href="/topic/instruction1">使用教程</a>            <span class="item">联系我们</span>            <a href="">联系方式</a>            <a href="">意见反馈</a>        </p>        <p class="copyright">Copyright ©2018  All Rights Reserved. 浙ICP备16009637号-3.</p>    </div></footer>

</body></html>

templates/topic/policy.html
<!DOCTYPE html>

<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0"><link rel="shortcut icon" href="../../static/topic/index/static/images/notebook_ico.ico" type="image/x-icon" />
    <title>复盘笔记本 - 每日数据</title>
    <meta name="keywords" content="复盘笔记本,数据可视化，股市量化分析">
    <meta name="description" content="复盘笔记本产品slogan">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/font-awesome.min.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/base.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/page.css">
       <link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
</head>
<body class="oneday">
<div class="placeHeader"></div>
<header>
    <div class="logo"><img src="../../static/topic/index/static/images/notebook.png"><p>复盘笔记本</p><div class="clear"></div></div>
<ul class="menu">
    <li class="curMenu"><a href="/topic">建仓or清仓?(大盘异动)</a></li>
    <li ><a href="/topic1">换仓?(短期情绪)</a></li>
    <li><a href="/topic2">辅助工具</a></li>
  <li><a href="/topic/instruction1">使用说明</a></li>
    </ul>
<ul class="account">
    <li><a href="/topic2/user">我的账户</a></li>
 <li><a href="/">退出</a></li>
</ul>
<style>
    .mb2{
	text-align:center;
}
    .submit {
	padding: 6px;
	width:100px;
}
    .time{
    float:right;
    padding-right:20px;
    }
    .text1 {
    padding: 3px;
    border: 1px solid #cdcdcd;
    width: 700px;
}

</style></header>
<section class="contain">
    <aside>
        <ul>
            <li class="menu1"><a href="/topic">总结</a></li>
            <li class="menu2"><a href="/topic/admin">指数价量异动</a></li>
            <li class="menu3"><a href="/topic/weight">权重异动</a></li>
            <li class="menu4 curMenu"><a href="/topic/policy">政策及权重调控</a></li>
        </ul>
    </aside>
    <section class="main" id="main">
        <div class="dateSelect">
            <span>政策及权重调控(对资金的影响)</span>
        </div>
        <section class="content tab">
            <div class="listThCover"><span></span></div>
            <ul class="list">
                <li class="th">
                     <ul>
                        <li class="td1"><span>影响版块</span></li>
                        <li class="td2">&nbsp</li>
                        <li class="td3"><a  class="sort" stype="sz">权重异动</a></li>
                        <li class="td4"><a  class="sort down" stype="time">热点龙头异动</a></li>
                        <li class="td4"><a  class="sort down" stype="time">顶或底部幅度</a></li>
                        <li class="td4"><a  class="sort down" stype="time">催化时间</a></li>
                        <li class="td7">政策</li>
                    </ul>
                </li>
            </ul>
                <ul class="list" id="gpList">
                {% for x in u %}
                <li class="tr ops" aid="undefined">
                    <ul><li class="td1">
                            {{x.section}}
                    </li>
                        <li class="td2" style="color: #61a0ff;">
                            <a  href="{{ url_for('topic.delete1', id=x.id, token=token) }}">
                                删除
                            </a>
                        </li>
                        <li class="td3">
                            {{x.weight_name}}
                        </li>
                        <li class="td4">
                            {{x.hot_name}}
                        </li>
                         <li class="td4">
                            {{x.position}}
                        </li>
                         <li class="td4">
                            {{x.time}}
                        </li>
                        <li class="td7">
                            {{x.policy}}
                        </li>
                    </ul>
                </li>
                {% endfor %}
                </ul>

        </section>
        <section class="content tab">
            <div class="listThCover"><span></span></div>
            <ul class="list">
                <li class="th">
                    <ul>
                        <li class="td1"><span>影响版块</span></li>
                        <li class="td2">&nbsp</li>
                        <li class="td3"><a  class="sort" stype="sz">权重异动</a></li>
                        <li class="td4"><a  class="sort down" stype="time">热点龙头异动</a></li>
                        <li class="td4"><a  class="sort down" stype="time">顶或底部幅度</a></li>
                        <li class="td4"><a  class="sort down" stype="time">催化时间</a></li>
                        <li class="td7">政策</li>
                    </ul>
                </li>
            </ul>
            <form class="form-horizontal" method="post" action="{{ url_for('.policy_index') }}">
                <ul class="list" id="gpList">
                <li class="tr ops" aid="undefined">
                    <ul>
                        <li class="td1">
                        <input name="section" class="text" type="text" value="影响版块/总结">
                        </li>
                        <li class="td2" style="color: #61a0ff;">
                         <input name="delect" class="text" type="text" value="" disabled>
                        </li>
                        <li class="td3">
                            <input name="weight_name" class="text" type="text" value="权重异动">
                        </li>
                        <li class="td4">
                            <input name="hot_name" class="text" type="text" value="热点龙头异动">
                        </li>
                         <li class="td4">
                            <input name="position" class="text" type="text" value="顶部或底部幅度">
                        </li>
                         <li class="td4">
                            <input name="time" class="text" type="text" value="催化时间">
                        </li>
                        <li class="td7">
                            <input name="policy" class="text1" type="text" value="政策">
                        </li>
                    </ul>
                </li>
                </ul>
                <div class="mb2">
                    <input type="submit" class="act-but submit" value="提交" id="btn_register">
                </div>
            </form>
        </section>
    </section>
</section>

<footer>    <div class="contain">        <p class="title">            <span class="item">关于我们</span>            <a href="/topic/instruction1">使用教程</a>            <span class="item">联系我们</span>            <a href="">联系方式</a>            <a href="">意见反馈</a>        </p>        <p class="copyright">Copyright ©2018  All Rights Reserved. 浙ICP备16009637号-3.</p>    </div></footer>

templates/topic/weight.html
<!DOCTYPE html>

<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0"><link rel="shortcut icon" href="../../static/topic/index/static/images/notebook_ico.ico" type="image/x-icon" />
    <title>复盘笔记本 - 每日数据</title>
    <meta name="keywords" content="复盘笔记本,数据可视化，股市量化分析">
    <meta name="description" content="复盘笔记本产品slogan">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/font-awesome.min.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/base.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/page.css">
       <link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
</head>
<body class="oneday">
<div class="placeHeader"></div>
<header>
    <div class="logo"><img src="../../static/topic/index/static/images/notebook.png"><p>复盘笔记本</p><div class="clear"></div></div>
<ul class="menu">
    <li class="curMenu"><a href="/topic">建仓or清仓?(大盘异动)</a></li>
    <li ><a href="/topic1">换仓?(短期情绪)</a></li>
    <li><a href="/topic2">辅助工具</a></li>
  <li><a href="/topic/instruction1">使用说明</a></li>
    </ul>
<ul class="account">
    <li><a href="/topic2/user">我的账户</a></li>
 <li><a href="/">退出</a></li>
</ul>
<style>
    .mb2{
	text-align:center;
}
    .submit {
	padding: 6px;
	width:100px;
}
    .time{
    float:right;
    padding-right:20px;
    }
    .text1 {
    padding: 3px;
    border: 1px solid #cdcdcd;
    width: 700px;
}

</style></header>
<section class="contain">
    <aside>
        <ul>
           <li class="menu1"><a href="/topic">总结</a></li>
            <li class="menu2"><a href="/topic/admin">指数价量异动</a></li>
            <li class="menu3 curMenu"><a href="/topic/weight">权重异动</a></li>
            <li class="menu4"><a href="/topic/policy">政策及权重调控</a></li>
        </ul>
    </aside>
    <section class="main" id="main">
        <div class="dateSelect">
            <span>
                <a href="http://www.iwencai.com/stockpick/search?typed=1&preParams=&ts=1&f=1&qs=result_rewrite&selfsectsn=&querytype=stock&searchfilter=&tid=stockpick&w=%E8%87%AA%E7%94%B1%E6%B5%81%E9%80%9A%E5%B8%82%E5%80%BC%E5%A4%A7%E4%BA%8E400%E4%BA%BF%20&queryarea=" target="_blank">权重异动 (自由流通市值大于400亿)</a>
                &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
                <a href="http://www.iwencai.com/stockpick/search?typed=0&preParams=&ts=1&f=1&qs=result_original&selfsectsn=&querytype=stock&searchfilter=&tid=stockpick&w=%E8%82%A1%E4%B8%9C%E6%88%B7%E6%95%B0%E7%8E%AF%E6%AF%94%E4%B8%8B%E9%99%8D%E8%B6%855%25%20%E8%87%AA%E7%94%B1%E6%B5%81%E9%80%9A%E5%B8%82%E5%80%BC%E5%A4%A7%E4%BA%8E200%E4%BA%BF%2030%E5%A4%A9%E4%B9%8B%E5%86%85%E6%B6%A8%E5%B9%85&queryarea=" target="_blank">权重跟踪:季度股东人数下降(200亿)</a>
            </span>
        </div>
        <section class="content tab">
            <div class="listThCover"><span></span></div>
            <ul class="list">
                <li class="th">
                    <ul>
                        <li class="td1"><span>版块</span></li>
                        <li class="td2">&nbsp</li>
                        <li class="td3"><a  class="sort" stype="sz">量能异动</a></li>
                        <li class="td4"><a  class="sort down" stype="time">中枢</a></li>
                        <li class="td4"><a  class="sort down" stype="time">顶/底/中部</a></li>
                        <li class="td4"><a  class="sort down" stype="time"> 上/下影线</a></li>
                        <li class="td7">股票简称</li>
                    </ul>
                </li>
            </ul>
                <ul class="list" id="gpList">
                {% for x in u %}
                <li class="tr ops" aid="undefined">
                    <ul><li class="td1">
                            {{x.section}}
                    </li>
                        <li class="td2" style="color: #61a0ff;">
                            <a  href="{{ url_for('topic.delete', id=x.id, token=token) }}">
                                删除
                            </a>
                        </li>
                        <li class="td3">
                            {{x.quantity}}
                        </li>
                        <li class="td4">
                            {{x.central}}
                        </li>
                         <li class="td4">
                            {{x.position}}
                        </li>
                         <li class="td4">
                            {{x.line}}
                        </li>
                        <li class="td7">
                            {{x.name}}
                        </li>
                    </ul>
                </li>
                {% endfor %}
                </ul>

        </section>
        <section class="content tab">
            <div class="listThCover"><span></span></div>
            <ul class="list">
                <li class="th">
                    <ul>
                        <li class="td1"><span>版块</span></li>
                        <li class="td2">&nbsp</li>
                        <li class="td3"><a  class="sort" stype="sz">量能异动</a></li>
                        <li class="td4"><a  class="sort down" stype="time">中枢</a></li>
                        <li class="td4"><a  class="sort down" stype="time">顶/底/中部</a></li>
                        <li class="td4"><a  class="sort down" stype="time">上/下阴线</a></li>
                        <li class="td7">股票简称</li>
                    </ul>
                </li>
            </ul>
            <form class="form-horizontal" method="post" action="{{ url_for('.weight_index') }}">
                <ul class="list" id="gpList">
                <li class="tr ops" aid="undefined">
                    <ul>
                        <li class="td1">
                        <input name="section" class="text" type="text" value="版块/总结">
                        </li>
                        <li class="td2" style="color: #61a0ff;">
                            <input name="delect" class="text" type="text" value="" disabled>
                        </li>
                        <li class="td3">
                            <input name="quantity" class="text" type="text" value="放量/缩量">
                        </li>
                        <li class="td4">
                            <input name="central" class="text" type="text" value="中枢">
                        </li>
                         <li class="td4">
                            <input name="position" class="text" type="text" value="顶/底/中部">
                        </li>
                         <li class="td4">
                            <input name="line" class="text" type="text" value="上下影线">
                        </li>
                        <li class="td7">
                            <input name="name" class="text1" type="text" value="股票简称/总结">
                        </li>
                    </ul>
                </li>
                </ul>
                <div class="mb2">
                    <input type="submit" class="act-but submit" value="提交" id="btn_register">
                </div>
            </form>
        </section>
    </section>
</section>

<footer>    <div class="contain">        <p class="title">            <span class="item">关于我们</span>            <a href="/topic/instruction1">使用教程</a>            <span class="item">联系我们</span>            <a href="">联系方式</a>            <a href="">意见反馈</a>        </p>        <p class="copyright">Copyright ©2018  All Rights Reserved. 浙ICP备16009637号-3.</p>    </div></footer>