models/supervision.py
from models.mongua import Mongua



class Supervision(Mongua):
    __fields__ =__fields__ = Mongua.__fields__ + [
        ('group', str, ''),
        ('name', str, ''),
        ('rank', str, ''),
        ('stock', str, ''),
        ('period', str, ''),
        ('tips', str, ''),
    ]

    def __init__(self):
        pass

    @classmethod
    # 存入指数
    def supervision_register(cls, form):
        u = Supervision.new(form)
        return u

models/user.py
from models.mongua import Mongua
import hashlib



class User(Mongua):
    __fields__ = Mongua.__fields__ + [
        ('username', str, ''),
        ('password', str, ''),
        ('user_image', str, ''),
    ]

    def __init__(self):
        pass

    #加密密码
    def salted_password(self, password, salt='$!@><?>HUI&DWQa`'):
        def sha256(ascii_str):
            return hashlib.sha256(ascii_str.encode('ascii')).hexdigest()
        hash1 = sha256(password)
        hash2 = sha256(hash1 + salt)
        return hash2

    #返回摘要字符串
    def hashed_password(self, pwd):
        p = pwd.encode('ascii')
        s = hashlib.sha256(p)
        return s.hexdigest()

    @classmethod
    #用户名不能为重,密码大于6个字符
    def register(cls, form):
        name = form.get('username', '')
        pwd = form.get('password', '')
        if  30 > len(name) > 3 and User.find_by(username=name) is None:
            u = User.new(form)
            u.password = u.salted_password(pwd)
            u.save()
            return u
        else:
            return None

    @classmethod
    #密码验证
    def validate_login(cls, form):
        u = User()
        u.username = form.get('username', '')
        u.password =form.get('password', '')
        user = User.find_by(username=u.username)
        if user is not None and user.password == u.salted_password(u.password):
            return user
        else:
            return None

routes/topic2.py
from flask import (
    render_template,
    request,
    session,
    redirect,
    url_for,
    Blueprint,
)

from routes.broadcast import broadcast_all
from models.supervision import Supervision
from models.user import User
from routes.rat import name_find
from routes.rat import second_analyze


from models.mongua import mongua
from routes.index import current_user,login_client



main = Blueprint('topic2', __name__)


#统计组的类型
def group_cell():
    uid = session.get('user_id', -1)
    group_mongo = mongua.xx['Supervision'].aggregate([
        { '$match': {'deleted': False}},
        {'$match': {'user_id': uid}},
        {'$group': {
            '_id': {
                'group': '$group',
            },
        }},
    ])
    group_list = list(g['_id'].get('group') for g in group_mongo)
    print('group_list', group_list)
    return group_list

#获取最新指数价量异动
@main.route('/')
def index2():
    if login_client():
        return redirect(url_for('index.index'))
    return render_template('topic2/index2.html')

@main.route('/user')
def user():
    if login_client():
        return redirect(url_for('index.index'))
    uid = session.get('user_id', -1)
    uu = User.find_by(id = uid)
    return render_template('topic2/user.html', u=uu)

@main.route('/ranklist')
def ranklist():
    if login_client():
        return redirect(url_for('index.index'))
    return render_template('topic2/ranklist.html')

@main.route('/update')
def update():
    if login_client():
        return redirect(url_for('index.index'))
    uid = session.get('user_id', -1)
    if uid == -10086:
        pass
    else:
        broadcast_all()
    return redirect(url_for('topic.index'))

@main.route('/analyze')
def analyze():
    if login_client():
        return redirect(url_for('index.index'))
    name_list = session.get('name_list','请先进行季报协同分析')
    return render_template('topic2/analyze.html',na = name_list)


@main.route('/front_running', methods = ['POST'])
def front_running():
    if login_client():
        return redirect(url_for('index.index'))
    form = request.form
    code=form['stock']
    qua = form['quarter']
    yea = int(form['year'])
    if qua == "{}.12.31-{}.03.31":
        quar = qua.format(int(yea-1), yea)
    else:
        quar = qua.format(yea, yea)
    coopers, name_set_list = name_find(code, quar)
    name_set_list = ','.join(name_set_list)
    cooper_new = {}
    for k,v in coopers.items():
        v = ','.join(v)
        cooper_new[k] = v
    session['name_list'] = name_set_list
    return render_template('topic2/front_running.html', uu = cooper_new, ss = name_set_list)

@main.route('/front_running2', methods = ['POST'])
def front_running2():
    if login_client():
        return redirect(url_for('index.index'))
    form = request.form
    name_str=form['list']
    name_list = name_str.split(',')
    name_set_all,all_coper_dict = second_analyze(name_list)
    cooper_new = {}
    for k,v in all_coper_dict.items():
        v[1] = ','.join(v[1])
        cooper_new[k] = v
    print('个人协同分析', cooper_new)
    return render_template('topic2/front_running2.html',
                           uu = cooper_new,
                           ss = ','.join(name_list),
                           pp = ','.join(name_set_all),
                           )


@main.route('/supervision_register', methods = ['POST'])
def supervision_register():
    if login_client():
        return redirect(url_for('index.index'))
    form = request.form
    group = form['group']
    Supervision.supervision_register(form)
    return redirect(url_for('.superv',groups = group))

@main.route('/supervision')
def supervision():
    if login_client():
        return redirect(url_for('index.index'))
    return redirect(url_for('topic2.superv', groups = 'groups'))

@main.route('/supervision/<groups>')
def superv(groups):
    if login_client():
        return redirect(url_for('index.index'))
    uid = session.get('user_id', -1)
    group_list = group_cell()
    uu = Supervision.find_all(user_id=uid, group=groups)
    return render_template('topic2/supervision.html', u =uu, s = group_list )


@main.route("/delete")
def delete():
    id = int(request.args.get('id'))
    uid = session.get('user_id', -1)
    w = Supervision.find_one(id = id, user_id = uid)
    Supervision.delete(w)
    return redirect(url_for('.supervision'))

templates/topic2/analyze.html
<!DOCTYPE html>

<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0"><link rel="shortcut icon" href="../../static/topic/index/static/images/notebook_ico.ico" type="image/x-icon" />
    <title>复盘笔记本 - 每日数据</title>
    <meta name="keywords" content="复盘笔记本,数据可视化，股市量化分析">
    <meta name="description" content="复盘笔记本产品slogan">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/font-awesome.min.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/base.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/page.css">
       <link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
        <script type="text/javascript">
function disp_alert()
{
alert("个人协同分析可能需要2到5分钟" + "\n" + "请稍等" + "\n" + '点击确定开始')
}
</script>
</head>

<body class="oneday">
<div class="placeHeader"></div>
<header>
    <div class="logo"><img src="../../static/topic/index/static/images/notebook.png"><p>复盘笔记本</p><div class="clear"></div></div>
<ul class="menu">
   <li ><a href="/topic">建仓or清仓?(大盘异动)</a></li>
    <li><a href="/topic1">换仓?(短期情绪)</a></li>
    <li class="curMenu"><a href="/topic2">辅助工具</a></li>
  <li><a href="/topic/instruction1">使用说明</a></li>
    </ul>
<ul class="account">
    <li><a href="/topic2/user">我的账户</a></li>
 <li><a href="/">退出</a></li>
</ul>
<style>
    .mb2{
	text-align:center;
}
    .submit {
	padding: 6px;
	width:100px;
}
    .time{
    float:right;
    padding-right:20px;
    }
    button, input, select, textarea {
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
    width: 80%;
    height: 34px;
}

</style></header>
<section class="contain">
    <aside>
        <ul>
       <li class="menu1 "><a href="/topic2">季报协同分析</a></li>
            <li class="menu2 curMenu" ><a href="/topic2/analyze">个人协同分析</a></li>
            <li class="menu3"><a href="/topic2/supervision">季报协同监控</a></li>
            <li class="menu4"><a href="/topic2/ranklist">龙虎榜自动关联</a></li>
        </ul>
    </aside>
    <section class="main" id="main">
        <div class="dateSelect">
            <span>个人协同分析</span>(对近20年数据进行分析,可能需要2到5分钟,含
            <a href="http://data.eastmoney.com/zlsj/qfii.html">QFII</a>
            会极大减慢分析速度,请删除
            <a href="http://data.eastmoney.com/zlsj/qfii.html">QFII</a>
            )
        </div>
        <section class="content tab">
            <form class="form-horizontal" method="post" action="{{ url_for('.front_running2') }}">
                <li class="td9">
                    <span>分析列表:</span><input name="list" class="text1" type="text" value="{{na}}">
                </li>
                <br>
</select>
                <br>
                <br>
                <div class="mb2">
                    <input type="submit" class="act-but submit" onclick="disp_alert()" value="协同分析" id="btn_register">
                </div>

            </form>
        </section>
    </section>

</section>

<footer>    <div class="contain">        <p class="title">            <span class="item">关于我们</span>            <a href="/topic/instruction1">使用教程</a>            <span class="item">联系我们</span>            <a href="">联系方式</a>            <a href="">意见反馈</a>        </p>        <p class="copyright">Copyright ©2018  All Rights Reserved. 浙ICP备16009637号-3.</p>    </div></footer>

templates/topic2/front_running.html
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0"><link rel="shortcut icon" href="../../static/topic/index/static/images/notebook_ico.ico" type="image/x-icon" />
    <title>复盘笔记本 - 每日数据</title>
    <meta name="keywords" content="复盘笔记本,数据可视化，股市量化分析">
    <meta name="description" content="复盘笔记本产品slogan">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/font-awesome.min.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/base.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/page.css">
       <link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">

</head>
<body class="oneday">
<div class="placeHeader"></div>
<header>
    <div class="logo"><img src="../../static/topic/index/static/images/notebook.png"><p>复盘笔记本</p><div class="clear"></div></div>
<ul class="menu">
    <li class="curMenu"><a href="/topic">建仓or清仓?(大盘异动)</a></li>
    <li ><a href="/topic1">换仓?(短期情绪)</a></li>
    <li><a href="/topic2">辅助工具</a></li>
  <li><a href="/topic/instruction1">使用说明</a></li>
    </ul>
<ul class="account">
    <li><a href="/topic2/user">我的账户</a></li>
 <li><a href="/">退出</a></li>
</ul>
<style>
    .mb2{
	text-align:center;
}
    .submit {
	padding: 6px;
	width:100px;
}
    .time{
    float:right;
    padding-right:20px;
    }
    .text1 {
    padding: 3px;
    border: 1px solid #cdcdcd;
    width: 700px;
}
.oneday section.contain section.main section.content ul.list li ul li.td11 {
    width: 80%;
    text-align: center;
}
    .butcent {
    text-align:center;
}



</style></header>
<section class="contain">
    <aside>
        <ul>
           <li class="menu1 curMenu"><a href="/topic2">季报协同分析</a></li>
            <li class="menu2" ><a href="/topic2/analyze">个人协同分析</a></li>
     <li class="menu3"><a href="/topic2/supervision">季报协同监控</a></li>
            <li class="menu4"><a href="/topic2/ranklist">龙虎榜自动关联</a></li>
        </ul>
    </aside>
    <section class="main" id="main">
        <div class="dateSelect">
            <span>协同分析(快速30s)</span>
        </div>
        <section class="content tab">
            <div class="listThCover"><span></span></div>
            <ul class="list">
                <li class="th">
                     <ul>
                        <li class="td1"><span>协同个股</span></li>
                        <li class="td11">协同股东</li>
                    </ul>
                </li>
            </ul>
                <ul class="list" id="gpList">
                {% for k,v in uu.items() %}
                <li class="tr ops" aid="undefined">
                    <ul><li class="td1">
                            {{k}}
                    </li>
                        <li class="td11">
                            {{v}}
                        </li>
                    </ul>
                </li>
                {% endfor %}
                    <li class="tr ops" aid="undefined">
                    <ul><li class="td1">
                            汇总
                    </li>
                        <li class="td11">
                            {% if ss %}
                                    {{ss}}
                                {% else %}
                                 未查询到关联股东
                                {% endif %}

                        </li>
                    </ul>
                </li>
                </ul>
        </section>
        <li class='butcent'>
         <span><a class="btn btn-default  btn-lg active" role="button" href="/topic2/analyze" target="_blank">个人协同分析</a></span>
        </li>
    </section>
</section>

<footer>    <div class="contain">        <p class="title">            <span class="item">关于我们</span>            <a href="/topic/instruction1">使用教程</a>            <span class="item">联系我们</span>            <a href="">联系方式</a>            <a href="">意见反馈</a>        </p>        <p class="copyright">Copyright ©2018  All Rights Reserved. 浙ICP备16009637号-3.</p>    </div></footer>

templates/topic2/front_running2.html
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0"><link rel="shortcut icon" href="../../static/topic/index/static/images/notebook_ico.ico" type="image/x-icon" />
    <title>复盘笔记本 - 每日数据</title>
    <meta name="keywords" content="复盘笔记本,数据可视化，股市量化分析">
    <meta name="description" content="复盘笔记本产品slogan">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/font-awesome.min.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/base.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/page.css">
       <link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">

</head>
<body class="oneday">
<div class="placeHeader"></div>
<header>
    <div class="logo"><img src="../../static/topic/index/static/images/notebook.png"><p>复盘笔记本</p><div class="clear"></div></div>
<ul class="menu">
    <li class="curMenu"><a href="/topic">建仓or清仓?(大盘异动)</a></li>
    <li ><a href="/topic1">换仓?(短期情绪)</a></li>
    <li><a href="/topic2">辅助工具</a></li>
  <li><a href="/topic/instruction1">使用说明</a></li>
    </ul>
<ul class="account">
    <li><a href="/topic2/user">我的账户</a></li>
 <li><a href="/">退出</a></li>
</ul>
<style>
    .mb2{
	text-align:center;
}
    .submit {
	padding: 6px;
	width:100px;
}
    .time{
    float:right;
    padding-right:20px;
    }
    .text1 {
    padding: 3px;
    border: 1px solid #cdcdcd;
    width: 700px;
}
.oneday section.contain section.main section.content ul.list li ul li.td11 {
    width: 75%;
    text-align: center;
    overflow:auto;
    text-overflow: clip;
}



</style></header>
<section class="contain">
    <aside>
        <ul>
        <li class="menu1 curMenu"><a href="/topic2">季报协同分析</a></li>
            <li class="menu2" ><a href="/topic2/analyze">个人协同分析</a></li>
         <li class="menu3"><a href="/topic2/supervision">季报协同监控</a></li>
            <li class="menu4"><a href="/topic2/ranklist">龙虎榜自动关联</a></li>
        </ul>
    </aside>
    <section class="main" id="main">
        <div class="dateSelect">
            <span>个人协同分析</span>
        </div>
        <section class="content tab">
            <div class="listThCover"><span></span></div>
            <ul class="list">
                <li class="th">
                     <ul>
                        <li class="td1"><span>股东</span></li>
                         <li class="td1"><span>协同股东</span></li>
                        <li class="td11"><span>关联个股</span></li>
                    </ul>
                </li>
            </ul>
                <ul class="list" id="gpList">
                {% for k,v in uu.items() %}
                <li class="tr ops" aid="undefined">
                    <ul>
                        <li class="td1">
                            {{v[0]}}
                    </li>
                        <li class="td1">
                            {{k}}
                    </li>
                        <li class="td11">
                            {{v[1]}}
                        </li>
                    </ul>
                </li>
                {% endfor %}
                    <li class="tr ops" aid="undefined">
                    <ul>
                        <li class="td1">
                            季度协同分析汇总
                    </li>
                        <li class="td1">
                            &nbsp
                    </li>
                        <li class="td11">
                            {{ss}}
                        </li>
                    </ul>
                </li>
                     <li class="tr ops" aid="undefined">
                    <ul>
                        <li class="td1">
                            个人协同分析汇总
                    </li>
                        <li class="td1">
                            &nbsp
                    </li>
                        <li class="td11">
                            {{pp}}
                        </li>
                    </ul>
                </li>

                </ul>
        </section>
  <li class='butcent'>
         <span><a class="btn btn-default  btn-lg active" role="button" href="/topic2/supervision" target="_blank">添加到季报协同监控</a></span>
        </li>
    </section>
</section>

<footer>    <div class="contain">        <p class="title">            <span class="item">关于我们</span>            <a href="/topic/instruction1">使用教程</a>            <span class="item">联系我们</span>            <a href="">联系方式</a>            <a href="">意见反馈</a>        </p>        <p class="copyright">Copyright ©2018  All Rights Reserved. 浙ICP备16009637号-3.</p>    </div></footer>

templates/topic2/supervision.html
<!DOCTYPE html>

<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0"><link rel="shortcut icon" href="../../static/topic/index/static/images/notebook_ico.ico" type="image/x-icon" />
    <title>复盘笔记本 - 每日数据</title>
    <meta name="keywords" content="复盘笔记本,数据可视化，股市量化分析">
    <meta name="description" content="复盘笔记本产品slogan">
    <meta http-equiv="Cache-Control" content="no-transform">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/font-awesome.min.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/base.css">
    <link rel="stylesheet" href="../../static/topic/index/static/css/page.css">
    <link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">


</head>
<body class="oneday">
<div class="placeHeader"></div>
<header>
    <div class="logo"><img src="../../static/topic/index/static/images/notebook.png"><p>复盘笔记本</p><div class="clear"></div></div>
<ul class="menu">
    <li><a href="/topic">建仓or清仓?(大盘异动)</a></li>
    <li ><a href="/topic1">换仓?(短期情绪)</a></li>
    <li class="curMenu"><a href="/topic2">辅助工具</a></li>
  <li><a href="/topic/instruction1">使用说明</a></li>
    </ul>
<ul class="account">
    <li><a href="/topic2/user">我的账户</a></li>
 <li><a href="/">退出</a></li>
</ul>
<style>
    .mb2{
	text-align:center;
}
    .submit {
	padding: 6px;
	width:100px;
}
    .time{
    float:right;
    padding-right:20px;
    }
    .text1 {
    padding: 3px;
    border: 1px solid #cdcdcd;
    width: 700px;
}

section.contain section.main div.dateSelect1{
	width: 100%;
	height: 60px;
	line-height: 60px;
	margin-bottom: 20px;
	background-color: #fff;
	display:inline;
	margin-right:22px;
}

.btn-default.active, .btn-default:active, .open>.dropdown-toggle.btn-default {
    color: #333;
    background-color: #e6e6e6;
    border-color: #adadad;
    margin-left: 22px;
}
.oneday section.contain section.main section.content ul.list li ul li.td11 {
    width: 75%;
    text-align: center;
    overflow:auto;
    text-overflow: clip;
}
.oneday section.contain section.main section.content ul.list li ul li.td1 {
    width: 12%;
    text-align: center;
    overflow: auto;
    text-overflow: clip;
}
ul.list>li {
    width: 100%;
    height: 60px;
    line-height: 40px;
    text-align: center;
}
</style></header>
<section class="contain">
    <aside>
        <ul>
         <li class="menu1 "><a href="/topic2">季报协同分析</a></li>
            <li class="menu2" ><a href="/topic2/analyze">个人协同分析</a></li>
            <li class="menu3 curMenu"><a href="/topic2/supervision">季报协同监控</a></li>
            <li class="menu4"><a href="/topic2/ranklist">龙虎榜自动关联</a></li>
        </ul>
    </aside>
    <section class="main" id="main">
        <div class="dateSelect">
            <!--<a 2018年3月31日到2018年6月30日 涨幅大于50% 上市天数大于200天>-->
            <span>
                <a href="http://www.iwencai.com/stockpick/search?typed=1&preParams=&ts=1&f=1&qs=result_rewrite&selfsectsn=&querytype=stock&searchfilter=&tid=stockpick&w=2018%E5%B9%B43%E6%9C%8831%E6%97%A5%E5%88%B02018%E5%B9%B46%E6%9C%8830%E6%97%A5%20%E6%B6%A8%E5%B9%85%E5%A4%A7%E4%BA%8E50%25%20%E4%B8%8A%E5%B8%82%E5%A4%A9%E6%95%B0%E5%A4%A7%E4%BA%8E200%E5%A4%A9&queryarea=" target="_blank">季度Top涨幅</a>:
   <a href="http://data.eastmoney.com/gdfx/" target="_blank">股东监控</a>
</span>
        </div>
        <div class="dateSelect1">
              {% for x in s %}
            <span><a class="btn btn-default  btn-lg active" role="button" href="/topic2/supervision/{{x}}">{{x}}</a></span>
               {% endfor %}
        </div>
        <br>
        <br>
        <section class="content tab">
            <div class="listThCover"><span></span></div>
            <ul class="list">
                <li class="th">
                    <ul>
                        <li class="td1"><span>姓名</span></li>
                        <li class="td2">&nbsp</li>
                        <li class="td3"><a  class="sort" stype="sz">跟踪价值</a></li>
                        <li class="td4"><a  class="sort down" stype="time">代表作</a></li>
                        <li class="td4"><a  class="sort down" stype="time">代表作时间</a></li>
                        <li class="td4"><a  class="sort down" stype="time"> 组</a></li>
                        <li class="td7">备注</li>
                    </ul>
                </li>
            </ul>
                <ul class="list" id="gpList">
                {% for x in u %}
                <li class="tr ops" aid="undefined">
                    <ul><li class="td1">
                         <a href="
http://www.yidiancangwei.com/searchResult.php?ID=1&Val={{x.name}}
" target="_blank">{{x.name}}</a>
                    </li>
                        <li class="td2" style="color: #61a0ff;">
                            <a  href="{{ url_for('topic2.delete', id=x.id, token=token) }}">
                                删除
                            </a>
                        </li>
                        <li class="td3">
                            {{x.rank}}
                        </li>
                        <li class="td4">
                            {{x.stock}}
                        </li>
                         <li class="td4">
                            {{x.period}}
                        </li>
                         <li class="td4">
                            {{x.group}}
                        </li>
                        <li class="td7">
                            {{x.tips}}
                        </li>
                    </ul>
                </li>
                {% endfor %}
                </ul>

        </section>
            <section class="content tab">
            <div class="listThCover"><span></span></div>
            <ul class="list">
                <li class="th">
                    <ul>
                         <li class="td1"><span>姓名</span></li>
                        <li class="td2">&nbsp</li>
                        <li class="td3"><a  class="sort" stype="sz">跟踪价值</a></li>
                        <li class="td4"><a  class="sort down" stype="time">代表作</a></li>
                        <li class="td4"><a  class="sort down" stype="time">代表作时间</a></li>
                        <li class="td4"><a  class="sort down" stype="time"> 组</a></li>
                        <li class="td7">备注</li>
                    </ul>
                </li>
            </ul>
            <form class="form-horizontal" method="post" action="{{ url_for('.supervision_register') }}">
                <ul class="list" id="gpList">
                <li class="tr ops" aid="undefined">
                    <ul>
                        <li class="td1">
                        <input name="name" class="text" type="text" value="姓名">
                        </li>
                        <li class="td2" style="color: #61a0ff;">
                         <input name="" class="text" type="text" value="" disabled>
                        </li>
                        <li class="td3">
                            <input name="rank" class="text" type="text" value="30%">
                        </li>
                        <li class="td4">
                            <input name="stock" class="text" type="text" value="上证50">
                        </li>
                         <li class="td4">
                            <input name="period" class="text" type="text" value="时间段">
                        </li>
                         <li class="td4">
                            <input name="group" class="text" type="text" value="组">
                        </li>
                        <li class="td7">
                            <input name="tips" class="text1" type="text" value="备注">
                        </li>
                    </ul>
                </li>
                </ul>
                <div class="mb2">
                    <input type="submit" class="act-but submit" value="提交" id="btn_register">
                </div>
            </form>
        </section>
    </section>
</section>

<footer>    <div class="contain">        <p class="title">            <span class="item">关于我们</span>            <a href="/topic/instruction1">使用教程</a>            <span class="item">联系我们</span>            <a href="">联系方式</a>            <a href="">意见反馈</a>        </p>        <p class="copyright">Copyright ©2018  All Rights Reserved. 浙ICP备16009637号-3.</p>    </div></footer>